name: Deno
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - run: deno fmt --check shm.ts shm.test.ts
      - run: deno lint
      - run: deno cache shm.test.ts
      - run: deno test -A --unstable-kv
