name: Deploy generated RSS to Pages

run-name: cron "${{ github.event.schedule }}"

# UTC (09:47-03:47 JST weekdays)
on:
  schedule:
    - cron: '47 0 * * 1-5'
    - cron: '47 1 * * 1-5'
    - cron: '47 2 * * 1-5'
    - cron: '47 3 * * 1-5'
    - cron: '47 4 * * 1-5'
    - cron: '47 5 * * 1-5'
    - cron: '47 6 * * 1-5'
    - cron: '47 7 * * 1-5'
    - cron: '47 8 * * 1-5'
    - cron: '47 9 * * 1-5'
    - cron: '47 10 * * 1-5'
    - cron: '47 11 * * 1-5'
    - cron: '47 12 * * 1-5'
    - cron: '47 18 * * 1-5'
    - cron: '47 4,10 * * 0,6'

  # Runs on pushes targeting the default branch
  # push:
  #   branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: gem install nokogiri

      - name: Make RSS
        run: ruby ./shm.rb && mkdir _site && cp shm.rss _site && cp shm.html _site/index.html

      - id: diff
        continue-on-error: true
        run: |
          mkdir prev
          curl -s https://tamo.github.io/shm-rss/shm.rss | diff -u - shm.rss

      - if: steps.diff.conclusion == 'failure'
        uses: actions/configure-pages@v4
      - if: steps.diff.conclusion == 'failure'
        uses: actions/upload-pages-artifact@v2
      - if: steps.diff.conclusion == 'failure'
        id: deployment
        uses: actions/deploy-pages@v3
